### PR TITLE
decouple business logic

### PR DESCRIPTION
**Pull request by libesz**
Hey!
I would propose a change to decompose the business logic from the HAL dependent parts.

The motivation is to be able to use just the core logic, if needed. I have a project where I am using a lot of rotaries and ran out of real MCU pins. So that I read them through shift-registers. and I was not able to properly set up fake `OutputPin`s with this setup in a way, where it could be moved into the `RotaryEncoder` instances.

After this change, the user is able to use `RotaryEncoderCore::<StandardMode>::new()` directly and just feed it with the bool inputs. I tested it and works great.

I did the change for `StandardMode` first, to have something to discuss, but the approach should also work with the angular mode as well.

### CODE REVIEW

**Comment by ost-ing** [comment]
Hey @libesz !

Thanks for the suggestion, I totally agree, we should have this library decoupled from the Pin traits and just pass `bool`s instead. Although I would go with a slightly simplified different approach

I think it would be better just to remove reference to the Pins entirely from both `StandardMode` and and `AngularMode`, and simply pass bools to the `update` function.

Then once that logic is decoupled, RotaryEncoder could be renamed "RotaryEncoderCore" and then create another wrapping struct "RotaryEncoder" that consumes the pins. 

Wdyt?

**Comment by libesz** [comment]
Hey!
 Thanks for the input. I am not sure how your suggestion is different than what is in the PR 😄 sorry.

So I removed the reference to the Pins in `StandardMode` and just using bool inputs from the caller: https://github.com/ostenning/rotary-encoder-embedded/pull/9/files#diff-cf82145bdc03093795bf0aed602b62f5e6932d28918e683430af047df946b914R21
This will also work with `AngularMode`.

The `RotaryEncoder` is now an owner of both an instance of the core logic and the Pins. It is feeding the core logic with bools. This way the library should be fully backward compatible, while the core logic can be used on it's own.

**Comment by libesz** [comment]
Hey @ostenning !
Let me ping this one. I don't get how your suggestion is different from mine. Please let me know ☺️

**Comment by ost-ing** [comment]
@libesz Sorry for the delay & thanks for the contribution!

**Comment by libesz** [comment]
No issues, thanks for taking another look! I hope this is 100% fine also for any other use-cases.

However, I did not refactor the angular velocity version of the logic in this PR. I will look into the updates of that as well and post it in another PR, hopefully soon. 🤞

**Comment by ost-ing** [comment]
@libesz there were issues with the angular velocity stuff, so I've fixed that. Basically you can now just use the StandardMode or AngularVelocityMode directly and bypass the pins. See the README for how to do this.
Thanks!

**Pull request merged**
